export const styles = {
  // Global background
  baseContainer: {
    minHeight: "100vh",
    width: "100vw",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    padding: "20px",
    boxSizing: "border-box",
    fontFamily: "system-ui, -apple-system, sans-serif",
    overflowX: "hidden", 
  },
  // Centering wrapper for Login only
  authWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "calc(100vh - 40px)",
  },
  // Layout wrapper for Library/Profile
  pageWrapper: {
    maxWidth: "1200px",
    margin: "0 auto",
    width: "100%",
  },
  card: {
    width: "100%",
    maxWidth: "400px",
    background: "white",
    borderRadius: "16px",
    padding: "40px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    marginBottom: "30px",
    textAlign: "center",
    color: "#333",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#555",
  },
  input: {
    padding: "12px",
    borderRadius: "8px",
    border: "2px solid #e0e0e0",
    fontSize: "16px",
    transition: "border-color 0.3s",
    outline: "none",
  },
  button: {
    padding: "14px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "transform 0.2s",
    marginTop: "10px",
  },
  error: {
    color: "#e74c3c",
    fontSize: "14px",
    textAlign: "center",
    margin: "10px 0",
  },
  switchText: {
    textAlign: "center",
    marginTop: "20px",
    fontSize: "14px",
    color: "#666",
  },
  link: {
    color: "#667eea",
    cursor: "pointer",
    fontWeight: "600",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "30px",
    flexWrap: "wrap",
    gap: "10px",
  },
  pageTitle: {
    fontSize: "32px",
    fontWeight: "bold",
    color: "white",
    margin: 0,
  },
  linkButton: {
    padding: "10px 20px",
    background: "white",
    color: "#667eea",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
  },
  searchBar: {
    marginBottom: "30px",
  },
  searchInput: {
    width: "100%",
    padding: "15px",
    borderRadius: "10px",
    border: "none",
    fontSize: "16px",
    boxShadow: "0 4px 15px rgba(0,0,0,0.2)",
  },
  movieGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", // Updated to look better
    gap: "30px",
    width: "100%",
  },
  movieCard: {
    background: "white",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: "0 4px 15px rgba(0,0,0,0.2)",
    transition: "transform 0.3s",
    cursor: "pointer",
  },
  moviePoster: {
    width: "100%",
    height: "350px",
    objectFit: "cover",
  },
  movieInfo: {
    padding: "15px",
  },
  movieTitle: {
    fontSize: "18px",
    fontWeight: "bold",
    margin: "0 0 5px 0",
    color: "#333",
  },
  movieDate: {
    fontSize: "14px",
    color: "#888",
    margin: "0 0 10px 0",
  },
  genreContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "5px",
    marginBottom: "10px",
  },
  genreBadge: {
    padding: "4px 10px",
    background: "#667eea",
    color: "white",
    borderRadius: "12px",
    fontSize: "12px",
  },
  movieDescription: {
    fontSize: "14px",
    color: "#666",
    lineHeight: "1.5",
  },
  noResults: {
    textAlign: "center",
    color: "white",
    fontSize: "18px",
    marginTop: "50px",
  },
  loadingText: {
    textAlign: "center",
    color: "white",
    fontSize: "18px",
    marginTop: "100px",
  },
  profileCard: {
    maxWidth: "600px",
    margin: "0 auto",
    background: "white",
    borderRadius: "16px",
    padding: "40px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
  },
  profileHeader: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    marginBottom: "30px",
  },
  avatar: {
    width: "80px",
    height: "80px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "36px",
    color: "white",
    fontWeight: "bold",
  },
  username: {
    fontSize: "24px",
    fontWeight: "bold",
    margin: "0 0 5px 0",
    color: "#333",
  },
  email: {
    fontSize: "16px",
    color: "#888",
    margin: 0,
  },
  profileStats: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
    marginBottom: "30px",
  },
  statItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "20px",
    background: "#f8f9fa",
    borderRadius: "12px",
  },
  statValue: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#667eea",
  },
  statLabel: {
    fontSize: "14px",
    color: "#888",
    marginTop: "5px",
  },
  logoutButton: {
    width: "100%",
    padding: "14px",
    background: "#e74c3c",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
  },
};