export const styles = {
  // Global background
  baseContainer: {
    minHeight: "100vh",
    width: "100vw",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    padding: "20px",
    boxSizing: "border-box",
    fontFamily: "system-ui, -apple-system, sans-serif",
    overflowX: "hidden", 
  },
  authWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "calc(100vh - 40px)",
  },
  pageWrapper: {
    maxWidth: "1200px",
    margin: "0 auto",
    width: "100%",
  },
  card: {
    width: "100%",
    maxWidth: "400px",
    background: "white",
    borderRadius: "16px",
    padding: "40px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    marginBottom: "30px",
    textAlign: "center",
    color: "#333",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#555",
  },
  input: {
    padding: "12px",
    borderRadius: "8px",
    border: "2px solid #e0e0e0",
    fontSize: "16px",
    transition: "border-color 0.3s",
    outline: "none",
  },
  textarea: {
    padding: "12px",
    borderRadius: "8px",
    border: "2px solid #e0e0e0",
    fontSize: "16px",
    transition: "border-color 0.3s",
    outline: "none",
    fontFamily: "system-ui, -apple-system, sans-serif",
    resize: "vertical",
  },
  button: {
    padding: "14px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "transform 0.2s",
    marginTop: "10px",
  },
  error: {
    color: "#e74c3c",
    fontSize: "14px",
    textAlign: "center",
    margin: "10px 0",
  },
  switchText: {
    textAlign: "center",
    marginTop: "20px",
    fontSize: "14px",
    color: "#666",
  },
  link: {
    color: "#667eea",
    cursor: "pointer",
    fontWeight: "600",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "30px",
    flexWrap: "wrap",
    gap: "10px",
  },
  pageTitle: {
    fontSize: "32px",
    fontWeight: "bold",
    color: "white",
    margin: 0,
  },
  linkButton: {
    padding: "10px 20px",
    background: "white",
    color: "#667eea",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
  },
  searchBar: {
    marginBottom: "30px",
  },
  searchInput: {
    width: "100%",
    padding: "15px",
    borderRadius: "10px",
    border: "none",
    fontSize: "16px",
    boxShadow: "0 4px 15px rgba(0,0,0,0.2)",
  },
  movieGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: "30px",
    width: "100%",
  },
  movieCard: {
    background: "white",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: "0 4px 15px rgba(0,0,0,0.2)",
    transition: "transform 0.3s",
    cursor: "pointer",
  },
  movieCardWrapper: {
    position: "relative",
  },
  starButton: {
    position: "absolute",
    top: "10px",
    right: "10px",
    background: "rgba(0,0,0,0.6)",
    border: "none",
    borderRadius: "50%",
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "gold",
    fontSize: "24px",
    transition: "transform 0.2s",
    zIndex: 10,
  },
  moviePoster: {
    width: "100%",
    height: "350px",
    objectFit: "cover",
  },
  movieInfo: {
    padding: "15px",
  },
  movieTitle: {
    fontSize: "18px",
    fontWeight: "bold",
    margin: "0 0 5px 0",
    color: "#333",
  },
  movieDate: {
    fontSize: "14px",
    color: "#888",
    margin: "0 0 10px 0",
  },
  genreContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "5px",
    marginBottom: "10px",
  },
  genreBadge: {
    padding: "4px 10px",
    background: "#667eea",
    color: "white",
    borderRadius: "12px",
    fontSize: "12px",
  },
  movieDescription: {
    fontSize: "14px",
    color: "#666",
    lineHeight: "1.5",
  },
  noResults: {
    textAlign: "center",
    color: "white",
    fontSize: "18px",
    marginTop: "50px",
  },
  loadingText: {
    textAlign: "center",
    color: "white",
    fontSize: "18px",
    marginTop: "100px",
  },
  profileCard: {
    maxWidth: "600px",
    margin: "0 auto",
    background: "white",
    borderRadius: "16px",
    padding: "40px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
  },
  profileHeader: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    marginBottom: "30px",
  },
  avatar: {
    width: "80px",
    height: "80px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "36px",
    color: "white",
    fontWeight: "bold",
  },
  username: {
    fontSize: "24px",
    fontWeight: "bold",
    margin: "0 0 5px 0",
    color: "#333",
  },
  email: {
    fontSize: "16px",
    color: "#888",
    margin: 0,
  },
  profileStats: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
    marginBottom: "30px",
  },
  statItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "20px",
    background: "#f8f9fa",
    borderRadius: "12px",
  },
  statValue: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#667eea",
  },
  statLabel: {
    fontSize: "14px",
    color: "#888",
    marginTop: "5px",
  },
  logoutButton: {
    width: "100%",
    padding: "14px",
    background: "#e74c3c",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
  },
  
  // NEW MOVIE DETAIL STYLES
  movieHero: {
    display: "flex",
    gap: "40px",
    background: "white",
    borderRadius: "16px",
    padding: "40px",
    marginBottom: "40px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
    flexWrap: "wrap",
  },
  movieDetailPoster: {
    width: "300px",
    height: "450px",
    objectFit: "cover",
    borderRadius: "12px",
    boxShadow: "0 8px 20px rgba(0,0,0,0.2)",
  },
  movieDetailInfo: {
    flex: 1,
    minWidth: "300px",
  },
  movieDetailTitle: {
    fontSize: "36px",
    fontWeight: "bold",
    margin: "0 0 10px 0",
    color: "#333",
  },
  movieDetailYear: {
    fontSize: "18px",
    color: "#888",
    margin: "0 0 15px 0",
  },
  movieDetailDescription: {
    fontSize: "16px",
    lineHeight: "1.6",
    color: "#555",
    marginTop: "20px",
  },
  ratingDisplay: {
    display: "flex",
    alignItems: "baseline",
    gap: "5px",
    marginTop: "20px",
  },
  ratingNumber: {
    fontSize: "48px",
    fontWeight: "bold",
    color: "#667eea",
  },
  ratingLabel: {
    fontSize: "24px",
    color: "#888",
  },
  ratingCount: {
    fontSize: "16px",
    color: "#999",
    marginLeft: "10px",
  },
  section: {
    marginBottom: "40px",
  },
  sectionTitle: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "white",
    marginBottom: "20px",
    paddingBottom: "10px",
    borderBottom: "3px solid rgba(255,255,255,0.3)",
  },
  castGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: "20px",
  },
  castCard: {
    background: "white",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: "0 4px 15px rgba(0,0,0,0.2)",
  },
  castPhoto: {
    width: "100%",
    height: "250px",
    objectFit: "cover",
  },
  castInfo: {
    padding: "15px",
  },
  castName: {
    fontSize: "16px",
    fontWeight: "bold",
    margin: "0 0 5px 0",
    color: "#333",
  },
  castRole: {
    fontSize: "14px",
    color: "#888",
    margin: 0,
  },
  relatedGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: "20px",
  },
  relatedCard: {
    background: "white",
    borderRadius: "12px",
    overflow: "hidden",
    cursor: "pointer",
    transition: "transform 0.3s",
    boxShadow: "0 4px 15px rgba(0,0,0,0.2)",
  },
  relatedPoster: {
    width: "100%",
    height: "300px",
    objectFit: "cover",
  },
  relatedTitle: {
    fontSize: "14px",
    fontWeight: "bold",
    padding: "10px",
    margin: 0,
    color: "#333",
  },
  reviewForm: {
    background: "white",
    borderRadius: "12px",
    padding: "20px",
    marginBottom: "30px",
    boxShadow: "0 4px 15px rgba(0,0,0,0.2)",
  },
  ratingInput: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  slider: {
    width: "100%",
    height: "8px",
    borderRadius: "4px",
    outline: "none",
    background: "#e0e0e0",
  },
  reviewsList: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  reviewCard: {
    background: "white",
    borderRadius: "12px",
    padding: "20px",
    boxShadow: "0 4px 15px rgba(0,0,0,0.2)",
  },
  reviewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "15px",
  },
  reviewTitle: {
    fontSize: "18px",
    fontWeight: "bold",
    margin: "0 0 5px 0",
    color: "#333",
  },
  reviewAuthor: {
    fontSize: "14px",
    color: "#888",
    margin: 0,
  },
  reviewRating: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#667eea",
    minWidth: "60px",
    textAlign: "right",
  },
  reviewText: {
    fontSize: "15px",
    lineHeight: "1.6",
    color: "#555",
    marginBottom: "10px",
  },
  reviewDate: {
    fontSize: "12px",
    color: "#999",
    margin: 0,
  },
};